project_name: bookhunter
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: bookhunter
    binary: bookhunter
    gcflags:
      - all=-l -B
    ldflags:
      - -s -w
      - -X github.com/bookstairs/bookhunter/cmd.gitVersion={{ .Version }}
      - -X github.com/bookstairs/bookhunter/cmd.gitCommit={{ .Commit }}
      - -X github.com/bookstairs/bookhunter/cmd.buildDate={{ .Date }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - loong64
    ignore:
      - goos: windows
        goarch: loong64
      - goos: darwin
        goarch: loong64

scoops:
  - repository:
      owner: bookstairs
      name: scoop-bucket
      branch: master
    commit_author:
      name: syhily
      email: syhily@gmail.com
    homepage: "https://github.com/bookstairs"
    description: "Software to download chinese ebooks from Internet."
    license: MIT

brews:
  - name: bookhunter
    repository:
      owner: bookstairs
      name: homebrew-tap
      branch: master
    commit_author:
      name: syhily
      email: syhily@gmail.com
    directory: Formula
    homepage: "https://github.com/bookstairs"
    description: "Software to download chinese ebooks from Internet."
    license: "MIT"
    install: |
      bin.install "bookhunter"

      # Install shell completions
      output = Utils.safe_popen_read("#{bin}/bookhunter", "completion", "bash")
      (bash_completion/"bookhunter").write output

      output = Utils.safe_popen_read("#{bin}/bookhunter", "completion", "zsh")
      (zsh_completion/"_bookhunter").write output

      output = Utils.safe_popen_read("#{bin}/bookhunter", "completion", "fish")
      (fish_completion/"bookhunter.fish").write output
    test: |
      system "#{bin}/bookhunter version"

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^web:'
      - '^build:'

archives:
  - id: bookhunter
    builds:
      - bookhunter
    format: tar.gz
    wrap_in_directory: "true"
    format_overrides:
      - goos: windows
        format: zip

release:
  draft: true

snapshot:
  version_template: "{{ incminor .Version }}-next"
